# Generated by Django 4.2.16 on 2026-05-16 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_function',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserFunctionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='function_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='core.function')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='function_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_user_function_history',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='function',
            field=models.ForeignKey(blank=True, db_column='function_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_users', to='core.function'),
        ),
    ]
