# Generated by Django 4.2.16 on 2026-05-16 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_function_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.function'),
        ),
    ]
