# Generated by Django 4.2.16 on 2026-05-10 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source_type', models.CharField(choices=[('regulatory', 'Regulatory'), ('operational', 'Operational'), ('strategic', 'Strategic'), ('financial', 'Financial'), ('emerging', 'Emerging')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('velocity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('assessment_stale', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_change_source', models.CharField(choices=[('manual', 'Manual'), ('system_triggered', 'System Triggered')], default='manual', max_length=20)),
            ],
            options={
                'db_table': 'risks_risk',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('expected_residual_rating', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_links', to='risk.control')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_treatments', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='risks.risk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risks_treatment',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_source', models.CharField(choices=[('manual', 'Manual'), ('system_triggered', 'System Triggered')], max_length=20)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_history_entries', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='risks.risk')),
            ],
            options={
                'db_table': 'risks_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('appetite', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('appetite_rationale', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_categories_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risks_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inherent_likelihood', models.IntegerField()),
                ('inherent_consequence', models.IntegerField()),
                ('inherent_rating', models.CharField(max_length=10)),
                ('residual_likelihood', models.IntegerField()),
                ('residual_consequence', models.IntegerField()),
                ('residual_rating', models.CharField(max_length=10)),
                ('target_likelihood', models.IntegerField()),
                ('target_consequence', models.IntegerField()),
                ('target_rating', models.CharField(max_length=10)),
                ('within_appetite', models.BooleanField()),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('rationale', models.TextField()),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('matrix_version_note', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments_made', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='risks.risk')),
            ],
            options={
                'db_table': 'risks_assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='risks.riskcategory'),
        ),
        migrations.AddField(
            model_name='risk',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risk',
            name='linked_obligations',
            field=models.ManyToManyField(blank=True, related_name='linked_risks', to='risk.obligation'),
        ),
        migrations.AddField(
            model_name='risk',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risk',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MatrixCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likelihood', models.IntegerField()),
                ('consequence', models.IntegerField()),
                ('rating', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
            ],
            options={
                'db_table': 'risks_matrix_cell',
                'ordering': ['likelihood', 'consequence'],
                'unique_together': {('likelihood', 'consequence')},
            },
        ),
        migrations.CreateModel(
            name='RiskControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_role', models.CharField(choices=[('preventive', 'Preventive'), ('detective', 'Detective'), ('corrective', 'Corrective')], max_length=20)),
                ('effectiveness', models.CharField(choices=[('strong', 'Strong'), ('adequate', 'Adequate'), ('weak', 'Weak'), ('untested', 'Untested')], max_length=20)),
                ('linkage_notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_controls_added', to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_controls', to='risk.control')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_controls', to='risks.risk')),
            ],
            options={
                'db_table': 'risks_risk_control',
                'unique_together': {('risk', 'control')},
            },
        ),
    ]
