# Generated by Django 4.2.16 on 2026-05-10 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_reference', models.CharField(max_length=100)),
                ('data_date', models.DateField()),
                ('uploaded_file', models.FileField(upload_to='data_imports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('validated', 'Validated'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='pending', max_length=20)),
                ('row_count_raw', models.PositiveIntegerField(blank=True, null=True)),
                ('row_count_valid', models.PositiveIntegerField(blank=True, null=True)),
                ('row_count_error', models.PositiveIntegerField(blank=True, null=True)),
                ('parse_started_at', models.DateTimeField(blank=True, null=True)),
                ('parse_completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'actuarial_data_import',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_code', models.CharField(max_length=50)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('fixed_width', 'Fixed Width')], default='csv', max_length=20)),
                ('delimiter', models.CharField(default=',', max_length=10)),
                ('has_header_row', models.BooleanField(default=True)),
                ('encoding', models.CharField(default='utf-8', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'actuarial_data_schema',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('field_order', models.PositiveIntegerField()),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=20)),
                ('date_format', models.CharField(blank=True, max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('is_primary_key', models.BooleanField(default=False)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('allowed_values', models.JSONField(blank=True, null=True)),
                ('fixed_width_start', models.PositiveIntegerField(blank=True, null=True)),
                ('fixed_width_end', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='actuarial.dataschema')),
            ],
            options={
                'db_table': 'actuarial_schema_field',
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='ImportValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('error_type', models.CharField(choices=[('missing_required', 'Missing Required'), ('wrong_type', 'Wrong Type'), ('out_of_range', 'Out of Range'), ('invalid_value', 'Invalid Value'), ('duplicate_primary_key', 'Duplicate Primary Key'), ('row_level', 'Row Level')], max_length=30)),
                ('raw_value', models.TextField(blank=True)),
                ('message', models.TextField()),
                ('data_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='actuarial.dataimport')),
            ],
            options={
                'db_table': 'actuarial_import_validation_error',
                'ordering': ['row_number', 'field_name'],
            },
        ),
        migrations.AddField(
            model_name='dataimport',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='actuarial.dataschema'),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PolicyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('primary_key_value', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('has_errors', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='actuarial.dataimport')),
            ],
            options={
                'db_table': 'actuarial_policy_record',
                'indexes': [models.Index(fields=['data_import', 'primary_key_value'], name='actuarial_p_data_im_53397b_idx'), models.Index(fields=['data_import'], name='actuarial_p_data_im_3121c8_idx')],
            },
        ),
    ]
