# Generated by Django 4.2.16 on 2026-05-10 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('control_type', models.CharField(choices=[('preventive', 'Preventive'), ('detective', 'Detective'), ('corrective', 'Corrective')], max_length=20)),
                ('frequency', models.CharField(choices=[('continuous', 'Continuous'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('ad_hoc', 'Ad Hoc')], max_length=20)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('operating', 'Operating'), ('not_operating', 'Not Operating'), ('not_tested', 'Not Tested'), ('retired', 'Retired')], default='operating', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'risk_control',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('verbatim_text', models.TextField()),
                ('interpretation', models.TextField()),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('implementation_notes', models.TextField(blank=True)),
                ('risk_rating', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_review', 'Under Review'), ('not_applicable', 'Not Applicable'), ('superseded', 'Superseded')], default='active', max_length=20)),
                ('review_due', models.DateField(blank=True, null=True)),
                ('last_change_source', models.CharField(choices=[('manual', 'Manual'), ('automated_feed', 'Automated Feed'), ('pending_review', 'Pending Review')], default='manual', max_length=20)),
                ('pending_update', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'risk_obligation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObligationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('legislation', 'Legislation'), ('prudential_standard', 'Prudential Standard'), ('asic_instrument', 'ASIC Instrument'), ('life_code', 'Life Code of Practice'), ('internal_policy', 'Internal Policy')], max_length=30)),
                ('issuing_body', models.CharField(max_length=255)),
                ('reference_url', models.URLField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='risk.obligationsource')),
            ],
            options={
                'db_table': 'risk_obligation_source',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObligationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField()),
                ('change_summary', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='risk.obligation')),
            ],
            options={
                'db_table': 'risk_obligation_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ObligationControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_controls', to='risk.control')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_controls', to='risk.obligation')),
            ],
            options={
                'db_table': 'risk_obligation_control',
                'unique_together': {('obligation', 'control')},
            },
        ),
        migrations.AddField(
            model_name='obligation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='risk.obligationsource'),
        ),
        migrations.AddField(
            model_name='control',
            name='obligations',
            field=models.ManyToManyField(related_name='controls', through='risk.ObligationControl', to='risk.obligation'),
        ),
    ]
